Resources:
  ImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.imagesBucketName}
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - '*'
              - 'https://netstrations.surge.sh'
            AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - HEAD

  ImagesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: ImagesBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
            Resource:
              - 'arn:aws:s3:::${self:custom.imagesBucketName}/*'

Outputs:
  ImagesBucketName:
    Value:
      Ref: ImagesBucket